title: Github Pages Test Three
description: Suffering is the first noble truth.
theme: just-the-docs

url: https://pranavkparti.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
